name: tbchessapp
description: "Play Chess Tournaments Near You"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  pocketbase: ^0.23.0
  shared_preferences: ^2.5.3
  go_router: ^16.0.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2
  url_launcher_web: ^2.4.1
  web: ^1.1.1
  flutter_otp_text_field: ^1.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
